// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sanrpc.proto

package sanrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SanrpcMagic int32

const (
	SanrpcMagic_SANRPC_DEFAULT_MAGIC_VALUE SanrpcMagic = 0
	SanrpcMagic_SANRPC_MAGIC_VALUE         SanrpcMagic = 5201314
)

var SanrpcMagic_name = map[int32]string{
	0:       "SANRPC_DEFAULT_MAGIC_VALUE",
	5201314: "SANRPC_MAGIC_VALUE",
}

var SanrpcMagic_value = map[string]int32{
	"SANRPC_DEFAULT_MAGIC_VALUE": 0,
	"SANRPC_MAGIC_VALUE":         5201314,
}

func (x SanrpcMagic) String() string {
	return proto.EnumName(SanrpcMagic_name, int32(x))
}

func (SanrpcMagic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{0}
}

type SanrpcContentEncodeType int32

const (
	SanrpcContentEncodeType_SANRPC_NONE_ENCODE SanrpcContentEncodeType = 0
	SanrpcContentEncodeType_SANRPC_PB_ENCODE   SanrpcContentEncodeType = 1
	SanrpcContentEncodeType_SANRPC_JSON_ENCODE SanrpcContentEncodeType = 2
)

var SanrpcContentEncodeType_name = map[int32]string{
	0: "SANRPC_NONE_ENCODE",
	1: "SANRPC_PB_ENCODE",
	2: "SANRPC_JSON_ENCODE",
}

var SanrpcContentEncodeType_value = map[string]int32{
	"SANRPC_NONE_ENCODE": 0,
	"SANRPC_PB_ENCODE":   1,
	"SANRPC_JSON_ENCODE": 2,
}

func (x SanrpcContentEncodeType) String() string {
	return proto.EnumName(SanrpcContentEncodeType_name, int32(x))
}

func (SanrpcContentEncodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{1}
}

type SanrpcCompressType int32

const (
	SanrpcCompressType_SANRPC_NONE_COMPRESS SanrpcCompressType = 0
	SanrpcCompressType_SANRPC_GZIP_COMPRESS SanrpcCompressType = 1
)

var SanrpcCompressType_name = map[int32]string{
	0: "SANRPC_NONE_COMPRESS",
	1: "SANRPC_GZIP_COMPRESS",
}

var SanrpcCompressType_value = map[string]int32{
	"SANRPC_NONE_COMPRESS": 0,
	"SANRPC_GZIP_COMPRESS": 1,
}

func (x SanrpcCompressType) String() string {
	return proto.EnumName(SanrpcCompressType_name, int32(x))
}

func (SanrpcCompressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{2}
}

type SanrpcMsgType int32

const (
	SanrpcMsgType_SANRPC_NONE_MSG     SanrpcMsgType = 0
	SanrpcMsgType_SANRPC_REQUEST_MSG  SanrpcMsgType = 1
	SanrpcMsgType_SANRPC_RESPONSE_MSG SanrpcMsgType = 2
)

var SanrpcMsgType_name = map[int32]string{
	0: "SANRPC_NONE_MSG",
	1: "SANRPC_REQUEST_MSG",
	2: "SANRPC_RESPONSE_MSG",
}

var SanrpcMsgType_value = map[string]int32{
	"SANRPC_NONE_MSG":     0,
	"SANRPC_REQUEST_MSG":  1,
	"SANRPC_RESPONSE_MSG": 2,
}

func (x SanrpcMsgType) String() string {
	return proto.EnumName(SanrpcMsgType_name, int32(x))
}

func (SanrpcMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{3}
}

type HeaderMsg struct {
	Version              uint32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CallType             uint32            `protobuf:"varint,2,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	Seq                  uint64            `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Timeout              uint32            `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ServiceName          string            `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName           string            `protobuf:"bytes,6,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	EncodeType           uint32            `protobuf:"varint,7,opt,name=encode_type,json=encodeType,proto3" json:"encode_type,omitempty"`
	CompressType         uint32            `protobuf:"varint,8,opt,name=compress_type,json=compressType,proto3" json:"compress_type,omitempty"`
	MetaData             map[string]string `protobuf:"bytes,9,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HeaderMsg) Reset()         { *m = HeaderMsg{} }
func (m *HeaderMsg) String() string { return proto.CompactTextString(m) }
func (*HeaderMsg) ProtoMessage()    {}
func (*HeaderMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{0}
}

func (m *HeaderMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderMsg.Unmarshal(m, b)
}
func (m *HeaderMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderMsg.Marshal(b, m, deterministic)
}
func (m *HeaderMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderMsg.Merge(m, src)
}
func (m *HeaderMsg) XXX_Size() int {
	return xxx_messageInfo_HeaderMsg.Size(m)
}
func (m *HeaderMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderMsg proto.InternalMessageInfo

func (m *HeaderMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HeaderMsg) GetCallType() uint32 {
	if m != nil {
		return m.CallType
	}
	return 0
}

func (m *HeaderMsg) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *HeaderMsg) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *HeaderMsg) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *HeaderMsg) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *HeaderMsg) GetEncodeType() uint32 {
	if m != nil {
		return m.EncodeType
	}
	return 0
}

func (m *HeaderMsg) GetCompressType() uint32 {
	if m != nil {
		return m.CompressType
	}
	return 0
}

func (m *HeaderMsg) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

type ErrMsg struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{1}
}

func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrMsg.Unmarshal(m, b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return xxx_messageInfo_ErrMsg.Size(m)
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ErrMsg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type MessageProtocol struct {
	Header               *HeaderMsg `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Err                  *ErrMsg    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Data                 []byte     `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageProtocol) Reset()         { *m = MessageProtocol{} }
func (m *MessageProtocol) String() string { return proto.CompactTextString(m) }
func (*MessageProtocol) ProtoMessage()    {}
func (*MessageProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_be86558a1b70b3c0, []int{2}
}

func (m *MessageProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageProtocol.Unmarshal(m, b)
}
func (m *MessageProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageProtocol.Marshal(b, m, deterministic)
}
func (m *MessageProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageProtocol.Merge(m, src)
}
func (m *MessageProtocol) XXX_Size() int {
	return xxx_messageInfo_MessageProtocol.Size(m)
}
func (m *MessageProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_MessageProtocol proto.InternalMessageInfo

func (m *MessageProtocol) GetHeader() *HeaderMsg {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MessageProtocol) GetErr() *ErrMsg {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *MessageProtocol) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("sanrpc.SanrpcMagic", SanrpcMagic_name, SanrpcMagic_value)
	proto.RegisterEnum("sanrpc.SanrpcContentEncodeType", SanrpcContentEncodeType_name, SanrpcContentEncodeType_value)
	proto.RegisterEnum("sanrpc.SanrpcCompressType", SanrpcCompressType_name, SanrpcCompressType_value)
	proto.RegisterEnum("sanrpc.SanrpcMsgType", SanrpcMsgType_name, SanrpcMsgType_value)
	proto.RegisterType((*HeaderMsg)(nil), "sanrpc.HeaderMsg")
	proto.RegisterMapType((map[string]string)(nil), "sanrpc.HeaderMsg.MetaDataEntry")
	proto.RegisterType((*ErrMsg)(nil), "sanrpc.ErrMsg")
	proto.RegisterType((*MessageProtocol)(nil), "sanrpc.MessageProtocol")
}

func init() { proto.RegisterFile("sanrpc.proto", fileDescriptor_be86558a1b70b3c0) }

var fileDescriptor_be86558a1b70b3c0 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x8d, 0x4d, 0x20, 0x78, 0x0c, 0x5f, 0xf8, 0x36, 0xa8, 0x71, 0x53, 0xa9, 0xa1, 0xf4, 0x42,
	0x39, 0x70, 0xa0, 0x97, 0xaa, 0xed, 0x85, 0x80, 0x0b, 0xa9, 0x62, 0xe3, 0xae, 0xa1, 0x87, 0x5e,
	0xac, 0xad, 0x59, 0x11, 0x54, 0x6c, 0x53, 0x7b, 0x83, 0xc4, 0xdf, 0xe9, 0xdf, 0xa8, 0xfa, 0xab,
	0xfa, 0x07, 0xaa, 0x9d, 0xb5, 0x89, 0xab, 0xde, 0x66, 0xde, 0xbc, 0x79, 0x7e, 0xfb, 0x46, 0x86,
	0x46, 0xc6, 0xe2, 0x74, 0x17, 0x0e, 0x76, 0x69, 0x22, 0x12, 0x52, 0x53, 0x5d, 0xf7, 0xb7, 0x0e,
	0xc6, 0x8c, 0xb3, 0x15, 0x4f, 0x9d, 0x6c, 0x4d, 0x2c, 0x38, 0xdb, 0xf3, 0x34, 0xdb, 0x24, 0xb1,
	0xa5, 0x75, 0xb4, 0x5e, 0x93, 0x16, 0x2d, 0x79, 0x06, 0x46, 0xc8, 0xb6, 0xdb, 0x40, 0x1c, 0x76,
	0xdc, 0xd2, 0x71, 0x56, 0x97, 0xc0, 0xe2, 0xb0, 0xe3, 0xa4, 0x05, 0x95, 0x8c, 0x7f, 0xb7, 0x2a,
	0x1d, 0xad, 0x77, 0x4a, 0x65, 0x29, 0x85, 0xc4, 0x26, 0xe2, 0xc9, 0x83, 0xb0, 0x4e, 0x95, 0x50,
	0xde, 0x92, 0x17, 0xd0, 0xc8, 0x78, 0xba, 0xdf, 0x84, 0x3c, 0x88, 0x59, 0xc4, 0xad, 0x6a, 0x47,
	0xeb, 0x19, 0xd4, 0xcc, 0x31, 0x97, 0x45, 0x9c, 0x5c, 0x83, 0x19, 0x71, 0x71, 0x9f, 0xac, 0x14,
	0xa3, 0x86, 0x0c, 0x50, 0x50, 0x41, 0xe0, 0x71, 0x98, 0xac, 0xb8, 0xb2, 0x73, 0x86, 0x5f, 0x00,
	0x05, 0xa1, 0xa1, 0x97, 0xd0, 0x0c, 0x93, 0x68, 0x97, 0xf2, 0x2c, 0x53, 0x94, 0x3a, 0x52, 0x1a,
	0x05, 0x88, 0xa4, 0xf7, 0x60, 0x44, 0x5c, 0xb0, 0x60, 0xc5, 0x04, 0xb3, 0x8c, 0x4e, 0xa5, 0x67,
	0x0e, 0xaf, 0x07, 0x79, 0x48, 0xc7, 0x48, 0x06, 0x0e, 0x17, 0x6c, 0xc2, 0x04, 0xb3, 0x63, 0x91,
	0x1e, 0x68, 0x3d, 0xca, 0xdb, 0xab, 0x77, 0xd0, 0xfc, 0x6b, 0x24, 0x43, 0xf8, 0xc6, 0x0f, 0x98,
	0x9b, 0x41, 0x65, 0x49, 0xda, 0x50, 0xdd, 0xb3, 0xed, 0x83, 0xca, 0xcb, 0xa0, 0xaa, 0x79, 0xab,
	0xbf, 0xd1, 0xba, 0x37, 0x50, 0xb3, 0x53, 0x4c, 0x9c, 0xc0, 0x29, 0x1a, 0x94, 0x6b, 0x55, 0x8a,
	0xb5, 0xc4, 0xe4, 0x4b, 0x70, 0xad, 0x4a, 0xb1, 0x96, 0xea, 0x51, 0xb6, 0xc6, 0x88, 0x0d, 0x2a,
	0xcb, 0x6e, 0x0a, 0xe7, 0x0e, 0xcf, 0x32, 0xb6, 0xe6, 0x9e, 0xbc, 0x68, 0x98, 0x6c, 0xc9, 0x2b,
	0xa8, 0xdd, 0xa3, 0x71, 0x94, 0x33, 0x87, 0xff, 0xff, 0xf3, 0x1c, 0x9a, 0x13, 0x48, 0x07, 0x2a,
	0x3c, 0x4d, 0xf1, 0x13, 0xe6, 0xf0, 0xbf, 0x82, 0xa7, 0x4c, 0x51, 0x39, 0x92, 0x2e, 0x30, 0x19,
	0x79, 0xbf, 0x06, 0xc5, 0xba, 0x3f, 0x03, 0xd3, 0x47, 0xa6, 0xc3, 0xd6, 0x9b, 0x90, 0x3c, 0x87,
	0x2b, 0x7f, 0xe4, 0x52, 0x6f, 0x1c, 0x4c, 0xec, 0x0f, 0xa3, 0xe5, 0xdd, 0x22, 0x70, 0x46, 0xd3,
	0xdb, 0x71, 0xf0, 0x79, 0x74, 0xb7, 0xb4, 0x5b, 0x27, 0xe4, 0x29, 0x90, 0x7c, 0x5e, 0xc6, 0x7f,
	0xfc, 0xfc, 0xa5, 0xf7, 0x03, 0xb8, 0x54, 0x4a, 0xe3, 0x24, 0x16, 0x3c, 0x16, 0xf6, 0xe3, 0xf1,
	0x9e, 0x1c, 0xb7, 0xdc, 0xb9, 0x6b, 0x07, 0xb6, 0x3b, 0x9e, 0x4f, 0xa4, 0x5a, 0x1b, 0x5a, 0x39,
	0xee, 0xdd, 0x14, 0xa8, 0x56, 0x62, 0x7f, 0xf4, 0xe7, 0x6e, 0x81, 0xeb, 0xfd, 0x19, 0x90, 0xe2,
	0x03, 0xa5, 0x9b, 0x5b, 0xd0, 0x2e, 0x6b, 0x8f, 0xe7, 0x8e, 0x47, 0x6d, 0xdf, 0x6f, 0x9d, 0x94,
	0x26, 0xd3, 0x2f, 0xb7, 0xde, 0xe3, 0x44, 0xeb, 0x2f, 0xa1, 0x99, 0x3f, 0x3a, 0x5b, 0xa3, 0xc8,
	0x05, 0x9c, 0x97, 0x45, 0x1c, 0x7f, 0xda, 0x3a, 0x29, 0xf9, 0xa0, 0xf6, 0xa7, 0xa5, 0xed, 0x2f,
	0x10, 0xd7, 0xc8, 0x25, 0x5c, 0x1c, 0x71, 0xdf, 0x9b, 0xbb, 0xbe, 0x5a, 0xd0, 0xbf, 0xd6, 0xf0,
	0x47, 0x7c, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0x56, 0xc6, 0x6c, 0x66, 0x98, 0x03, 0x00, 0x00,
}
